[{
    "startTime": 0,
    "title": "Intro",
    "index": 1
}, {
    "startTime": 37,
    "title": "Scenario_01",
    "index": 2
}, {
    "startTime": 64,
    "title": "Choice_01",
    "index": 3
}, {
    "startTime": 70,
    "title": "Scenario_02",
    "index": 4
}, {
    "startTime": 101,
    "title": "Choice_02",
    "index": 5
}, {
    "startTime": 107,
    "title": "Scenario_03",
    "index": 6
}, {
    "startTime": 146,
    "title": "Choice_03",
    "index": 7
}, {
    "startTime": 152,
    "title": "Scenario_04",
    "index": 8
}, {
    "startTime": 192,
    "title": "Choice_04",
    "index": 9
}, {
    "startTime": 198,
    "title": "Scenario_05",
    "index": 10
}, {
    "startTime": 231,
    "title": "Choice_05",
    "index": 11
}, {
    "startTime": 241,
    "title": "Scenario_06",
    "index": 12
}, {
    "startTime": 275,
    "title": "Choice_06",
    "index": 13
}, {
    "startTime": 285,
    "title": "Scenario_07",
    "index": 14
}, {
    "startTime": 313,
    "title": "Choice_07",
    "index": 15
}, {
    "startTime": 319,
    "title": "Answers",
    "index": 16
}]